# Assumes that 'terminal.yaml' has been run to set up fish & fisher
- hosts: localhost
  tasks:
    - name: Ensure Homebrew is installed
      community.general.homebrew:
        update_homebrew: yes

    - name: Install texlive
      community.general.homebrew:
        name: texlive
        state: present

    - name: Install adoptopenjdk
      community.general.homebrew_cask:
        name: adoptopenjdk
        state: present

    - name: Install swiftenv
      community.general.homebrew:
        name: kylef/formulae/swiftenv
        state: present
    - name: Add swiftenv to bash
      lineinfile:
        path: ~/.bash_profile
        line: "if which swiftenv > /dev/null; then eval \"$(swiftenv init -)\"; fi"
        state: present
    - name: Add swiftenv to zsh
      lineinfile:
        path: ~/.zshrc
        line: "if which swiftenv > /dev/null; then eval \"$(swiftenv init -)\"; fi"
        state: present
    - name: Add swiftenv to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        line: "if which swiftenv > /dev/null; status --is-interactive; and source (swiftenv init -|psub); end"
        state: present

    - name: Install pyenv
      community.general.homebrew:
        name: pyenv
        state: present
      register: pyenv_install_result
    - name: Add pyenv to bash
      lineinfile:
        path: ~/.bash_profile
        line: "eval \"$(pyenv init -)\""
        state: present
    - name: Add PYENV_ROOT to bash
      lineinfile:
        path: ~/.bash_profile
        line: "export PYENV_ROOT=\"$HOME/.pyenv\""
        state: present
    - name: Add pyenv to zsh
      lineinfile:
        path: ~/.zshrc
        line: "eval \"$(pyenv init -)\""
        state: present
    - name: Add PYENV_ROOT to zsh
      lineinfile:
        path: ~/.zshrc
        line: "export PYENV_ROOT=\"$HOME/.pyenv\""
        state: present
    - name: Add pyenv to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        line: "if which pyenv > /dev/null; status --is-interactive; and source (pyenv init -|psub); end"
        state: present
    - name: Add PYENV_ROOT to fish
      shell: |
        fish --command "set -Ux PYENV_ROOT $HOME/.pyenv"
      when: pyenv_install_result.changed

    - name: Install goenv
      community.general.homebrew:
        name: goenv
        state: present
      register: goenv_install_result
    - name: Add goenv to bash
      lineinfile:
        path: ~/.bash_profile
        line: "eval \"$(goenv init -)\""
        state: present
    - name: Add GOENV_ROOT to bash
      lineinfile:
        path: ~/.bash_profile
        line: "export GOENV_ROOT=\"$HOME/.goenv\""
        state: present
    - name: Add goenv to zsh
      lineinfile:
        path: ~/.zshrc
        line: "eval \"$(goenv init -)\""
        state: present
    - name: Add GOENV_ROOT to zsh
      lineinfile:
        path: ~/.zshrc
        line: "export GOENV_ROOT=\"$HOME/.goenv\""
        state: present
    - name: Add goenv to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        line: "if which goenv > /dev/null; status --is-interactive; and source (goenv init -|psub); end"
        state: present
    - name: Add GOENV_ROOT to fish
      shell: |
        fish --command "set -Ux GOENV_ROOT $HOME/.goenv"
      when: goenv_install_result.changed

    - name: Install jenv
      community.general.homebrew:
        name: jenv
        state: present
      register: jenv_install_result
    - name: Add jenv to bash
      lineinfile:
        path: ~/.bash_profile
        line: "eval \"$(jenv init -)\""
        state: present
    - name: Add jenv to zsh
      lineinfile:
        path: ~/.zshrc
        line: "eval \"$(jenv init -)\""
        state: present
    - name: Add jenv to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        line: "if which jenv > /dev/null; status --is-interactive; and source (jenv init -|psub); end"
        state: present

    - name: Install nvm
      community.general.homebrew:
        name: nvm
        state: present
    - name: Add nvm to bash
      blockinfile:
        path: ~/.bash_profile
        block: |
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
        state: present
    - name: Add nvm to zsh
      blockinfile:
        path: ~/.zshrc
        block: |
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
        state: present
    
    - name: Check for nvm in fish
      shell: fish --command "nvm -v"
      ignore_errors: yes
      register: nvm_check_result
      changed_when: nvm_check_result.failed
    - name: Install nvm.fish
      shell: fish --command "fisher install jorgebucaran/nvm.fish"
      when: nvm_check_result.failed