- hosts: localhost
  tasks:
    - name: Check homebrew
      shell: which brew
      ignore_errors: yes
      register: brew_check_result
      changed_when: brew_check_result.failed
    - name: Install homebrew
      shell: |
        export NONINTERACTIVE=1
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_check_result.changed
    
    # MacOS
    - name: Add homebrew to bash (MacOS)
      lineinfile:
        path: ~/.bash_profile
        line: test -d /opt/homebrew/bin && eval "$(/opt/homebrew/bin/brew shellenv)"
        state: present
      when: ansible_facts["os_family"] == "Darwin"
    
    # Linux
    - name: Add homebrew to bash (Linux)
      blockinfile:
        path: ~/.bash_profile
        block: |
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        state: present
      when: ansible_facts["os_family"] == "Debian"
    - name: Install brew dependencies
      ansible.builtin.apt:
        name: build-essential
        state: present
      become: true
      when: ansible_facts["os_family"] == "Debian"