- hosts: localhost
  tasks:
    
    # MacOS (Darwin)
    - name: Ensure Homebrew is installed
      community.general.homebrew:
        update_homebrew: yes
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - fzf
        - htop
        - jq
        - neovim
        - starship
        - yq
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install lsd
      community.general.homebrew:
        name: lsd
        state: present
      when: ansible_facts["os_family"] == "Darwin"
      register: lsd_install_result

    - name: Install font-hack-nerd-font
      community.general.homebrew_cask:
        name: font-hack-nerd-font
        state: present
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install fish
      community.general.homebrew:
        name: fish
        state: present
      register: fish_install_result
      when: ansible_facts["os_family"] == "Darwin"

    # Ubuntu (Debian)
    - name: Add apt repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      become: true
      when: ansible_facts["os_family"] == "Debian"
      loop:
        - ppa:fish-shell/release-3
    
    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes
      become: true
      when: ansible_facts["os_family"] == "Debian"

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - fzf
        - htop
        - jq
        - neovim
      become: true
      when: ansible_facts["os_family"] == "Debian"

    - name: Install snaps
      community.general.snap:
        name:
          - starship
          - yq
      become: true
    
    # TODO: LSD is only available in Ubuntu 23.04 :(
    - name: Install lsd
      ansible.builtin.apt:
        name: lsd
        state: present
      become: true
      when: ansible_facts["os_family"] == "Debian"
      register: lsd_install_result

    # TODO: Figure out how to install nerd fonts on Ubuntu

    - name: Install fish
      ansible.builtin.apt:
        name: fish
        state: present
      register: fish_install_result
      when: ansible_facts["os_family"] == "Debian"

    # General
    - name: Add fish to shells
      lineinfile:
        path: /etc/shells
        line: "/opt/homebrew/bin/fish"
        state: present
      become: true
    - name: Check for fisher
      shell: fish --command "fisher -v"
      ignore_errors: yes
      register: fisher_check_result
      changed_when: fisher_check_result.failed
    - name: Install fisher
      shell: fish --command "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
      when: fisher_check_result.failed

    - name: Add starship init to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        line: "starship init fish | source"
        state: present

    - name: Link neovim config
      file:
        src: ~/dev/config/alacritty
        dest: ~/.config/alacritty
        state: link

    - name: Add alias if lsd was installed or changed
      shell: |
        fish --command="alias --save ls='lsd'"
      when: lsd_install_result.changed