# Assumes that 'terminal.yaml' has been run to set up fish & fisher
- name: Development
  hosts: localhost
  tasks:
    - name: Ensure Homebrew is installed
      community.general.homebrew:
        update_homebrew: true

    - name: Install texlive
      community.general.homebrew:
        name: texlive
        state: present

    # Replaced by temurin
    - name: Uninstall adoptopenjdk
      community.general.homebrew_cask:
        name: adoptopenjdk
        state: uninstalled

    - name: Install temurin
      community.general.homebrew_cask:
        name: temurin
        state: present

    - name: Ensure bash_profile exists
      ansible.builtin.file:
        path: ~/.bash_profile
        state: touch
    - name: Ensure zshrc exists
      ansible.builtin.file:
        path: ~/.zshrc
        state: touch
    - name: Ensure fish config exists
      ansible.builtin.file:
        path: ~/.config/fish/config.fish
        state: touch

    # Replaced by swiftly
    - name: Uninstall swiftenv
      community.general.homebrew:
        name: kylef/formulae/swiftenv
        state: uninstalled
    - name: Add swiftenv block to bash
      ansible.builtin.blockinfile:
        block: |
          if which swiftenv > /dev/null; then eval \"$(swiftenv init -)\"; fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK: swiftenv"
        path: ~/.bash_profile
        state: absent
    - name: Add swiftenv block to zsh
      ansible.builtin.blockinfile:
        block: |
          if which swiftenv > /dev/null; then eval \"$(swiftenv init -)\"; fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK: swiftenv"
        path: ~/.zshrc
        state: absent
    - name: Add swiftenv block to fish
      ansible.builtin.blockinfile:
        block: |
          if which swiftenv > /dev/null; status --is-interactive; and source (swiftenv init -|psub); end
        marker: "# {mark} ANSIBLE MANAGED BLOCK: swiftenv"
        path: ~/.config/fish/config.fish
        state: absent

    - name: Install swiftly
      community.general.homebrew:
        name: swiftly
        state: present

    - name: Install pyenv
      community.general.homebrew:
        name: pyenv
        state: present
    - name: Add pyenv block to bash
      ansible.builtin.blockinfile:
        block: |
          eval "$(pyenv init -)"
          export PYENV_ROOT="$HOME/.pyenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        path: ~/.bash_profile
        state: present
    - name: Add pyenv block to zsh
      ansible.builtin.blockinfile:
        block: |
          eval "$(pyenv init -)"
          export PYENV_ROOT="$HOME/.pyenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        path: ~/.zshrc
        state: present
    - name: Add pyenv block to fish
      ansible.builtin.blockinfile:
        block: |
          if which pyenv > /dev/null; status --is-interactive; and source (pyenv init -|psub); end
          set -gx PYENV_ROOT $HOME/.pyenv
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        path: ~/.config/fish/config.fish
        state: present

    - name: Install goenv
      community.general.homebrew:
        name: goenv
        state: present
    - name: Add goenv block to bash
      ansible.builtin.blockinfile:
        block: |
          eval "$(goenv init -)"
          export GOENV_ROOT="$HOME/.goenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: goenv"
        path: ~/.bash_profile
        state: present
    - name: Add goenv block to zsh
      ansible.builtin.blockinfile:
        block: |
          eval "$(goenv init -)"
          export GOENV_ROOT="$HOME/.goenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: goenv"
        path: ~/.zshrc
        state: present
    - name: Add goenv block to fish
      ansible.builtin.blockinfile:
        block: |
          if which goenv > /dev/null; status --is-interactive; and source (goenv init -|psub); end
          set -gx GOENV_ROOT $HOME/.goenv
        marker: "# {mark} ANSIBLE MANAGED BLOCK: goenv"
        path: ~/.config/fish/config.fish
        state: present

    - name: Install jenv
      community.general.homebrew:
        name: jenv
        state: present
    - name: Add jenv block to bash
      ansible.builtin.blockinfile:
        block: |
          eval "$(jenv init -)"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: jenv"
        path: ~/.bash_profile
        state: present
    - name: Add jenv block to zsh
      ansible.builtin.blockinfile:
        block: |
          eval "$(jenv init -)"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: jenv"
        path: ~/.zshrc
        state: present
    - name: Add jenv block to fish
      ansible.builtin.blockinfile:
        block: |
          if which jenv > /dev/null; status --is-interactive; and source (jenv init -|psub); end
        marker: "# {mark} ANSIBLE MANAGED BLOCK: jenv"
        path: ~/.config/fish/config.fish
        state: present

    - name: Install nvm
      community.general.homebrew:
        name: nvm
        state: present
    - name: Add nvm block to bash
      ansible.builtin.blockinfile:
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
        marker: "# {mark} ANSIBLE MANAGED BLOCK: nvm"
        path: ~/.bashrc
        state: present
    - name: Add nvm block to zsh
      ansible.builtin.blockinfile:
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
        marker: "# {mark} ANSIBLE MANAGED BLOCK: nvm"
        path: ~/.zshrc
        state: present
    - name: Install nvm.fish
      ansible.builtin.shell: |
        fish --command "nvm -v" || \
        fish --command "fisher install jorgebucaran/nvm.fish"
      register: nvm_fish_result
      changed_when: nvm_fish_result.stdout is match("fisher")
