- name: DevOps
  hosts: localhost
  tasks:
    - name: Ensure Homebrew is installed
      community.general.homebrew:
        update_homebrew: true

    - name: Install terraform
      community.general.homebrew:
        name: terraform
        state: present
