- name: Terminal
  hosts: localhost
  tasks:
    - name: Ensure Homebrew is installed
      community.general.homebrew:
        update_homebrew: true
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - fzf
        - htop
        - jq
        - neovim
        - starship
        - yq
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install lsd
      community.general.homebrew:
        name: lsd
        state: present
      when: ansible_facts["os_family"] == "Darwin"
      notify: Add alias if lsd was installed or changed

    - name: Install font-hack-nerd-font
      community.general.homebrew_cask:
        name: font-hack-nerd-font
        state: present
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install fish
      community.general.homebrew:
        name: fish
        state: present
      register: fish_install_result
      when: ansible_facts["os_family"] == "Darwin"

    - name: Add fish to shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "/opt/homebrew/bin/fish"
        state: present
      become: true
    - name: Check for fisher
      ansible.builtin.raw: fish --command "fisher -v"
      check_mode: false
      changed_when: false
      failed_when: fisher_installed.rc > 0
      register: fisher_installed
    - name: Install fisher
      ansible.builtin.shell: |
        set -euo pipefail
        fish --command "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
      when: fisher_installed.rc > 0
      changed_when: true

    - name: Add starship init to fish
      ansible.builtin.lineinfile:
        path: ~/.config/fish/config.fish
        line: "starship init fish | source"
        state: present

    - name: Link neovim config
      ansible.builtin.file:
        src: ~/dev/config/nvim
        dest: ~/.config/nvim
        state: link
  handlers:
    - name: Add alias if lsd was installed or changed
      ansible.builtin.shell: |
        fish --command="alias --save ls='lsd'"
      changed_when: true
