- name: Terminal
  hosts: localhost
  tasks:
    - name: Install base apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg
        - gcc
      become: true

    - name: Add apt repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      become: true
      loop:
        - ppa:fish-shell/release-3
        - ppa:neovim-ppa/stable

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - fzf
        - htop
        - jq
        - neovim
      become: true

    - name: Install fish
      ansible.builtin.apt:
        name: fish
        state: present
      register: fish_install_result
      become: true
    - name: Add fish to shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "/usr/bin/fish"
        state: present
      become: true
    - name: Install fisher
      ansible.builtin.shell: |
        set -euo pipefail
        fish --command "fisher -v" || \
        fish --command "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
      register: fisher_result
      changed_when: fisher_result.stdout is match("fisher install")

    - name: Install yq
      ansible.builtin.shell: |
        which yq || (
          platform=$(uname -m)
          curl https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$platform -o /usr/bin/yq
          chmod +x /usr/bin/yq
        )
      become: true
      register: yq_result
      changed_when: yq_result.stdout is not regex(".*/yq")

    # TODO: LSD is only available in Ubuntu 23.04 :(
    # - name: Install lsd
    #   ansible.builtin.apt:
    #     name: lsd
    #     state: present
    #   become: true
    #   register: lsd_install_result
    # - name: Add alias if lsd was installed or changed
    #   ansible.builtin.shell: |
    #     fish --command="alias --save ls='lsd'"
    #   when: lsd_install_result.changed

    - name: Create font directory if it does not exist
      ansible.builtin.file:
        path: ~/.local/share/fonts
        state: directory
    - name: Check for hack font
      ansible.builtin.stat:
        path: ~/.local/share/fonts/HackNerdFont-Regular.ttf
      register: hack_font
    - name: Install hack fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz
        dest: ~/.local/share/fonts/
        remote_src: true
      when: not hack_font.stat.exists

    - name: Install starship
      ansible.builtin.shell: |
        set -euo pipefail
        which starship || \
        curl -sS https://starship.rs/install.sh | sh -s -- -f
      register: starship_result
      changed_when: starship_result.stdout is not regex(".*/starship")
    - name: Add starship init to fish
      ansible.builtin.lineinfile:
        path: ~/.config/fish/config.fish
        create: true
        line: "starship init fish | source"
        state: present

    - name: Link neovim config
      ansible.builtin.file:
        src: ~/dev/config/nvim
        dest: ~/.config/nvim
        state: link
