- hosts: localhost
  tasks:
    - name: Install base apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg
        - gcc
      become: true

    - name: Add apt repositories
      apt_repository:
        repo: "{{ item }}"
      become: true
      loop:
        - ppa:fish-shell/release-3
        - ppa:neovim-ppa/stable
    
    - name: Update apt
      apt:
        update_cache: yes
      become: true

    - name: Install fish
      apt:
        name: fish
        state: present
      register: fish_install_result
      become: true
    - name: Add fish to shells
      lineinfile:
        path: /etc/shells
        line: "/usr/bin/fish"
        state: present
      become: true
    - name: Install fisher
      shell: |
        fish --command "fisher -v" || \
        fish --command "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
      register: fisher_result
      changed_when: fisher_result.stdout is match("fisher install")

    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fzf
        - htop
        - jq
        - neovim
      become: true

    - name: Install yq
      shell: |
        which yq || (
          platform=$(uname -m)
          curl https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$platform -o /usr/bin/yq
          chmod +x /usr/bin/yq
        )
      become: true
      register: yq_result
      changed_when: yq_result.stdout is not regex(".*/yq")
    
    # TODO: LSD is only available in Ubuntu 23.04 :(
    # - name: Install lsd
    #   apt:
    #     name: lsd
    #     state: present
    #   become: true
    #   register: lsd_install_result
    # - name: Add alias if lsd was installed or changed
    #   shell: |
    #     fish --command="alias --save ls='lsd'"
    #   when: lsd_install_result.changed
    
    # TODO: Figure out how to install nerd fonts on Ubuntu

    - name: Install starship
      shell: |
        which starship || \
        curl -sS https://starship.rs/install.sh | sh -s -- -f
      register: starship_result
      changed_when: starship_result.stdout is not regex(".*/starship")
    - name: Add starship init to fish
      lineinfile:
        path: ~/.config/fish/config.fish
        create: true
        line: "starship init fish | source"
        state: present

    - name: Link neovim config
      file:
        src: ~/dev/config/nvim
        dest: ~/.config/nvim
        state: link