name: Formatting
"on":
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
permissions:
  contents: read
jobs:
  yaml-format:
    name: YAML Formatting
    runs-on: ubuntu-latest
    container:
      image: cytopia/yamlfmt:latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML formatting
        run: yamlfmt -lint .
  lua-format:
    name: Lua Formatting
    runs-on: ubuntu-latest
    container:
      image: johnnymorganz/stylua:latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Lua formatting
        run: stylua --check nvim/
