name: Formatting
"on":
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
permissions:
  contents: read
jobs:
  yaml-format:
    name: YAML Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML formatting
        run: docker run --rm -v $(pwd):/data cytopia/yamlfmt -lint .
  lua-format:
    name: Lua Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Lua formatting
        run: docker run --rm -v $(pwd):/data johnnymorganz/stylua stylua --check nvim/
